import type { EdgeBadgeStyle, ModeCurrentLook, PluginSetting, PluginValues } from '../../../core/plugins';
import { booleanValue, numberValue, stringValue } from '../../../core/plugins';

/** Réglages globaux du mode Séquences (Paramètres › Modes › Séquences, ticket 283). */
export const SEQUENCES_SETTINGS: PluginSetting[] = [
  {
    key: 'dimOpacity',
    type: 'number',
    group: 'Flux courant',
    label: 'Opacité hors du flux courant',
    hint: 'Flèches hors du flux courant et formes qu’aucune de ses flèches ne relie ; rien n’est estompé si le flux courant n’a pas de flèche.',
    min: 0.05,
    max: 1,
    step: 0.05,
    default: 0.3,
    unit: '%',
  },
  {
    key: 'barSlideDuration',
    type: 'number',
    label: 'Glissement de la barre du flux',
    hint: 'Pendant une transition entre pages, la barre remonte hors de la vue au départ et redescend à l’arrivée.',
    min: 0,
    max: 1000,
    step: 10,
    default: 200,
    unit: 'ms',
    zero: 'sans',
  },
  {
    key: 'badgeFaceCamera',
    type: 'toggle',
    group: 'Pastilles',
    groupHint: 'Rang d’une flèche dans son flux.',
    label: 'Pastille face à la caméra',
    default: true,
  },
  {
    key: 'badgeLabelFaceCamera',
    type: 'toggle',
    label: 'Texte des flèches en séquence face à la caméra',
    default: true,
  },
  {
    key: 'badgeBorderColor',
    type: 'color',
    label: 'Couleur de la bordure',
    default: '#000000',
  },
  {
    key: 'badgeBorderWidth',
    type: 'number',
    label: 'Épaisseur de la bordure',
    min: 0,
    max: 6,
    step: 0.5,
    default: 1,
    unit: 'px',
    zero: 'aucune',
  },
  {
    key: 'badgeTextColor',
    type: 'color',
    label: 'Couleur du chiffre',
    default: '#000000',
  },
  { key: 'badgeBold', type: 'toggle', label: 'Chiffre en gras', default: false },
  {
    key: 'badgeRadius',
    type: 'number',
    group: 'Pastille d’une flèche avec texte',
    label: 'Rayon',
    min: 3,
    max: 40,
    step: 0.5,
    default: 12,
    unit: 'px',
  },
  {
    key: 'badgeTextSize',
    type: 'number',
    label: 'Taille du chiffre',
    min: 4,
    max: 60,
    step: 1,
    default: 15,
    unit: 'px',
  },
  {
    key: 'badgeGap',
    type: 'number',
    label: 'Écart avec le texte',
    min: 0,
    max: 30,
    step: 1,
    default: 2,
    unit: 'px',
  },
  {
    key: 'badgeSmallRadius',
    type: 'number',
    group: 'Pastille d’une flèche sans texte',
    label: 'Rayon',
    min: 2,
    max: 20,
    step: 0.5,
    default: 5.5,
    unit: 'px',
  },
  {
    key: 'badgeSmallTextSize',
    type: 'number',
    label: 'Taille du chiffre',
    min: 3,
    max: 30,
    step: 1,
    default: 7,
    unit: 'px',
  },
  {
    key: 'edgeDarken',
    type: 'number',
    group: 'Flèches et couleurs',
    label: 'Assombrissement du trait',
    hint: 'Une flèche colorée par son flux prend cette couleur assombrie. Les couleurs des nouveaux flux sont les fonds des styles de forme, à partir du troisième.',
    min: 0,
    max: 0.9,
    step: 0.05,
    default: 0.25,
    unit: '%',
  },
  {
    key: 'plantumlRenderer',
    type: 'choice',
    group: 'Export PlantUML',
    label: 'Moteur de rendu',
    options: [
      { value: 'kroki', label: 'kroki.io' },
      { value: 'plantuml', label: 'plantuml.com' },
      { value: 'local', label: 'Serveur local' },
    ],
    default: 'kroki',
  },
  {
    key: 'plantumlUrl',
    type: 'url',
    label: 'URL du serveur local',
    when: { key: 'plantumlRenderer', value: 'local' },
    default: 'http://localhost:8080',
    hint: 'Rendu de la fenêtre d’export des flux. Le texte du diagramme part dans l’adresse de l’image : avec un serveur local, rien ne sort de la machine. Un serveur PlantUML se lance avec « make plantuml » (http://localhost:8080).',
  },
];

/** Apparence des pastilles d'après les réglages du mode. */
export function badgeStyle(values: PluginValues): EdgeBadgeStyle {
  return {
    radius: numberValue(values, 'badgeRadius'),
    textSize: numberValue(values, 'badgeTextSize'),
    smallRadius: numberValue(values, 'badgeSmallRadius'),
    smallTextSize: numberValue(values, 'badgeSmallTextSize'),
    borderColor: stringValue(values, 'badgeBorderColor'),
    borderWidth: numberValue(values, 'badgeBorderWidth'),
    textColor: stringValue(values, 'badgeTextColor'),
    bold: booleanValue(values, 'badgeBold'),
    gap: numberValue(values, 'badgeGap'),
    faceCamera: booleanValue(values, 'badgeFaceCamera'),
    labelFaceCamera: booleanValue(values, 'badgeLabelFaceCamera'),
  };
}

/** Apparence du flux courant d'après les réglages du mode. */
export function currentLook(values: PluginValues): ModeCurrentLook {
  return { dimOpacity: numberValue(values, 'dimOpacity'), barSlideDuration: numberValue(values, 'barSlideDuration') };
}
