import { DRAWIO_STYLES, PASTEL_STYLES, TEXT_STYLES } from '../edit/styles';
import { ISOMETRIC_ELEVATION_DEG } from '../interaction/camera';
import { DEFAULT_CONTROLS } from '../interaction/controls';
import { DEFAULT_DEPTH } from '../spatial';
import type { Settings } from './types';

/** Valeurs par défaut des paramètres (SPEC §13). */
export const DEFAULT_SETTINGS: Settings = {
  transition: { enabled: true, durationMs: 1000, easing: 'ease-in-out', fadeStart: 0.25, fadeEnd: 0.75 },
  preload: { onClick: true, onHover: false, hoverDelayMs: 300, maxCachedPages: 8 },
  controls: DEFAULT_CONTROLS,
  view: {
    defaultMode: 'top',
    isoAngleDeg: ISOMETRIC_ELEVATION_DEG,
    isoAzimuthDeg: -45,
    switchDurationMs: 450,
    isoVolume: true,
    isoDepth: DEFAULT_DEPTH,
    shadeLight: 0.9,
    shadeDark: 0.62,
    facadeTags: true,
  },
  camera: {
    minZoom: 0.05,
    maxZoom: 16,
    minZoom3d: 0.1,
    maxZoom3d: 4,
    maxTilt3dDeg: 65,
    fovDeg: 45,
    animationMs: 250,
    focusMaxZoom: 2,
    focusPadding: 80,
  },
  background: {
    color: '#ffffff',
    grid: true,
    gridFromPage: true,
    gridSize: 10,
    majorEvery: 4,
    gridColor: '#d4d9e0',
    minorStrength: 0.55,
  },
  minimap: { visible: true, size: 200, edgeColor: '#80868b', outlineColor: '#9aa0a6' },
  comment: {
    veilColor: '#202124',
    opacityCorner: 0.75,
    opacityEdge: 0.45,
    marginTop: 50,
    marginRight: 180,
    curveRadius: 230,
    fadeLength: 150,
    padding: 40,
    textColor: '#ffffff',
    textSize: 13,
    textMaxWidth: 340,
    fadeInMs: 220,
    fadeOutMs: 260,
  },
  selection: {
    style: 'veil',
    veilOpacity: 0.35,
    animated: true,
    speed: 12,
    veilColor: '#202124',
    veilPadding: 10,
    accentColor: '#1a73e8',
  },
  shapes: {
    edgeFontColor: '#000000',
    textSize: 12,
    edgeEndTextSize: 9,
    edgeEndTextColor: '#808080',
    edgeEndTextGapAlong: 6,
    edgeEndTextGapAcross: 4,
    edgeLineStyle: 'rounded',
    edgeJumpStyle: 'none',
    edgeJumpSize: 6,
    edgeAnchoring: 'manual',
    edgeAutoRoute: true,
    edgeShapeClearance: 10,
    edgeSpacing: 10,
    edgePortStub: 20,
    edgeCrossingDetour: 500,
    edgePcbAutoRoute: true,
    edgePcbShapeClearance: 10,
    edgePcbSpacing: 10,
    edgePcbPortStub: 20,
    edgePcbCrossingDetour: 500,
    edgePcbBend45: 15,
    edgePcbBend90: 30,
    edgeLoopMargin: 20,
    edgeLabelBackdrop: 'halo',
    edgeLabelHaloWidth: 1.5,
    edgeLabelHaloBlur: 1,
    edgeBadgeRadius: 12,
    edgeBadgeTextSize: 15,
    edgeBadgeSmallRadius: 5.5,
    edgeBadgeSmallTextSize: 7,
    edgeBadgeBorderColor: '#000000',
    edgeBadgeBorderWidth: 1,
    edgeBadgeTextColor: '#000000',
    edgeBadgeBold: false,
    edgeBadgeGap: 2,
    edgeBadgeFaceCamera: true,
    edgeBadgeLabelFaceCamera: true,
    edgeDressingDarken: 0.25,
    modeDimOpacity: 0.3,
    modeBarSlideDuration: 200,
    placeholderFill: '#eeeeee',
    placeholderStroke: '#9e9e9e',
  },
  styles: { base: DRAWIO_STYLES, extended: PASTEL_STYLES, text: TEXT_STYLES },
  graph: {
    cardWidth: 260,
    columnGap: 200,
    rowGap: 90,
    pairOffset: 16,
    cardColor: '#9aa0a6',
    orphanColor: '#d93025',
    unreachableColor: '#e37400',
    arcColor: '#5f6368',
    titleColor: '#202124',
  },
  edit: {
    edgePickTolerance: 6,
    handlePickTolerance: 8,
    handleSize: 4,
    minShapeSize: 10,
    nudgeStep: 1,
    nudgeCoarseStep: 0,
    alignReference: 'last',
    undoLimit: 100,
    pasteOffset: 10,
    edgePointAlignTolerance: 4,
    connectHandleOffset: 18,
    middleHandleMinSpan: 32,
  },
  save: { autosave: true, delayMs: 1000, viewStateDelayMs: 500, recentLimit: 20 },
  debug: { showUnsupportedPanel: true },
  accessibility: { reducedMotion: 'system' },
  panels: {
    left: { collapsed: false, width: 208 },
    right: { collapsed: false, width: 380 },
    stripText: 'up',
    shadow: 0.06,
    minCanvas: 320,
  },
  exporters: { plantuml: { renderer: 'kroki', localUrl: 'http://localhost:8080' } },
  effects: {},
};
